### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by HakumenNC** [adriens/imgflip4j#9]
Can you planned a jitpack release to 2.1?

fix :

* Infinite char #8

feat :

* `JsonFormat` on RankIcon enum 2bd92be4992acbf84dcae1c21a4e1d794c2b5b5e

Thanks ! 🙏🏽

**Comment by HakumenNC** [comment]
Hi, @adriens 🙏🏽

**Comment by adriens** [comment]
Yop @HakumenNC , here it is 👍 ⚡ 
![image](https://user-images.githubusercontent.com/5235127/131217015-819c3bcc-d714-486c-aef3-ad3b5fe154e0.png)

**Comment by HakumenNC** [comment]
Thanks @adriens 🤘🏽

**Comment by adriens** [comment]
The hardware is on tis way @HakumenNC  🚀 💣
